### ISSUE TITLE
Update python in setup_omaha.ps1

### ISSUE THREAD

**Issue by jumde** [brave/omaha-build#3]
https://github.com/brave/omaha-build/blob/master/vagrant/setup_omaha.ps1#L15

No critical vulns for Python 2.4: https://www.cvedetails.com/vulnerability-list/vendor_id-10210/product_id-18230/version_id-98372/Python-Python-2.4.4.html

But, good to update to - 2.7.14

**Comment by RyanJarv** [comment]
Not sure what the issues are with newer versions but I suspect this won't be trivial.

This seems to be what chrome uses and recommends (https://github.com/google/omaha/blame/master/doc/DeveloperSetupGuide.md#L27). Possible the docs may just have not been updated in a while so probably worth digging into more.
